name: Check and test Python package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    strategy:
      matrix:
        python-version:
            - "3.9"
            - "3.10"
            - "3.11"
            - "3.12"

    name: Check and test
    uses: greenbone/workflows/.github/workflows/ci-python.yml@main
    with:
      lint-packages: autohooks tests
      python-version: ${{ matrix.python-version }}
      test-command: "poetry run python -m pytest -v"


  codecov:
    name: Upload coverage to codecov.io
    # run action directly because GitHub has an internal error when using our
    # generic reusable workflow
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install
      - name: Install and calculate and upload coverage to codecov.io
        uses: greenbone/actions/coverage-python@v3
        with:
          python-version: "3.10"
          cache: "true"
          token: ${{ secrets.CODECOV_TOKEN }}
          test-command: "python -m pytest -v"
          install-dependencies: false

  versioning:
    name: Check versioning
    uses: greenbone/workflows/.github/workflows/check-version.yml@main
